SRC:
  catalog:
    host: 127.0.0.1
    port: 5432
    database: postgres
    username: pgadmin
    password: password
    lake_alias: lake
  storage:
    host: 127.0.0.1
    port: 9000
    scope: test
    secure: false
    region: us-east-1
    style: path
    access_key: minio
    secret: password



DEST:
  stream:
    host: 127.0.0.1
    port: 9092
    ingest_topics: 
      - test_topic
    ingest_table: kafka_src
    group_id: ducklake
  storage:
    host: 127.0.0.1
    port: 9000
    scope: destination
    secure: false
    region: us-east-1
    style: path
    access_key: minio
    secret: password
