services:
  pg:
    restart: unless-stopped
    image: postgres:16.3-bookworm
    container_name: pg
    ports:
      - 5432:5432
    networks:
      - pg_net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-p", "5432", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 3
  pgadmin:
    restart: unless-stopped
    image: dpage/pgadmin4:8.12
    container_name: pgadmin
    depends_on:
      pg:
        condition: service_healthy
    ports:
      - 8888:80
    networks:
      - pg_net
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-user@domain.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  minio:
    image: quay.io/minio/minio:RELEASE.2025-05-24T17-08-30Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-password}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
  
volumes:
  pg_data:
  pgadmin_data:
  minio_data:


networks:
  pg_net:
